### ISSUE TITLE
renderdepth.png and args.horizontal

### ISSUE THREAD

**Issue by qiminchen** [hjwdzh/FrameNet#3]
Hi Jingwei, thanks for the amazing code. I have a few questions about the dataset and train_affine_dorn. Would it be possible to release the depth.png? What is the `args.horizontal` in `train_affine_dorn.py` used for? Thank you.

**Comment by hjwdzh** [comment]
Our project is unrelated with the depth image/prediction. If you want to try depth estimation with our code, those images can be acquired from ScanNet.

Horizontal is a tricky thing. Basically, horizontal surfaces are those regions which are more "horizontal", or surfaces in which angles between the surface normal and gravity is smaller than 45 degree.

This is used for training the tangent directions. The story is that there is a natural ambiguity in the principal tangent directions (imagine a square room, there will be 4 directions at the floors). This ambiguity is harmful for training efficiency.

Fortunately, there is a clear definition of gravity vector for indoor scenes.

Therefore, we first train our network for those "non-horizontal" surfaces and estimate one of the four principal directions that closest to the gravity vector. This will give the network a good initialization. After that, we train all surfaces to predict any of the 4 directions.

**Comment by qiminchen** [comment]
thanks for the explanation.

it seems like `args.horizontal == 1` is never used since initially `args.horizontal == 0` and in the second epoch `args.horizontal == 2`?

By the way, how many epochs does the network need to be converged? I am training the net and it takes roughly 7 hr/epoch using single 2080ti with a batch size of 8.
