### ISSUE TITLE
question about quantitative results on the paper

### ISSUE THREAD

**Issue by qiminchen** [hjwdzh/FrameNet#5]
Hi, I noticed that in `AffineTestsDataset()` the test samples are drawn every 200 steps. I'm wondering if the quantitative results on the paper are evaluated on the whole test split or test samples from every 200 frames (322 images in total I think)? Thanks in advance.

https://github.com/hjwdzh/FrameNet/blob/fe5cc45148f210ad9a2520a576ad92f5f282ca71/src/dataset.py#L122-L131

**Comment by hjwdzh** [comment]
It's evaluated for all test split.
