### ISSUE TITLE
Different network architecture between paper and code ?

### ISSUE THREAD

**Issue by sandy-ssdut** [hjwdzh/FrameNet#7]
Hi,

I find that the network architecture is different in this code and the paper.

The paper said that FrameNet use DORN as backbone, and following with a U-Net style architecture. 

But in this code, there is only DORN backbone, no U-Net style architecture.

Why is this?

**Comment by hjwdzh** [comment]
The "U-Net" style means that we need a backbone that provides per-pixel feature. DORN is the actual backbone that we use.
