### ISSUE TITLE
How to get the principal preiction like these images in the data folder `demo/selected`?

### ISSUE THREAD

**Issue by lartpang** [hjwdzh/FrameNet#8]
It's a great work!
I want to try it on some images in demo downloaded by the script `/demo/download.sh`, but now, I cannot get as good results as the data `*-orient-X/Y_pred.png` provided in the `selected` folder...
Could you provide a more convenient script to get these results?

**Comment by hjwdzh** [comment]
It is directly computed from the pretrained model.
